name: Build and test

on:
  push:
    branches: [ giraffe-fork ]
  pull_request:
    branches: [ giraffe-fork ]


jobs:
  build-and-test-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
    - name: make script executable
      run: chmod u+x build.sh
    - name: Build and test
      working-directory: ./
      run: ./build.sh runtestsallnonetfx

  build-and-test-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
    - name: Build and test (includes netfx)
      working-directory: ./
      run: ./build.cmd runtestsall

  publish-nuget:
    needs: [build-and-test-linux, build-and-test-windows]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
    - name: Publish to GitHub Packages
      run: |
        ./build.sh PreReleaseNoDocs --prerelease-suffix=giraffe --non-interactive
      env:
        NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
        NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
